version: '3'
services:
  db:
    image: mcr.microsoft.com/mssql/server:2019-latest
    environment:
      ACCEPT_EULA: "Y"
      SA_PASSWORD: "MyStrongPassword!"
    ports:
      - "1433:1433"
  api:
    build: .
    depends_on:
      - db
    environment:
      DATABASE_HOST: localhost
      DATABASE_USERNAME: sa
      DATABASE_PASSWORD: MyStrongPassword!
      DATABASE_DB: nest_db
    ports:
      - "3000:3000"
    command: npm run start